-- Adding or removing a reusable section on a page is a real page edit: it produces a
-- new immutable Page Version and reconciles that page's Building Block usage rows in the
-- same transaction. Recording it under its own operation keeps History honest about what
-- happened — a section was composed, not regenerated by the agent — while still going
-- through the ordinary version-move replay, so Undo and Redo work on it unchanged.
ALTER TYPE change_set_operation ADD VALUE IF NOT EXISTS 'page_section_add';
ALTER TYPE change_set_operation ADD VALUE IF NOT EXISTS 'page_section_remove';
