/** @vitest-environment jsdom */
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { ActivityBar } from "./activity-bar";
import { PreviewStage } from "./preview-stage";
import { TitleBar } from "./title-bar";

beforeEach(() => { class Observer { observe() {} disconnect() {} } vi.stubGlobal("ResizeObserver", Observer); });
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });

describe("redesigned workspace chrome", () => {
  it("exposes every primary activity with names and selected state", () => { const select = vi.fn(); render(<ActivityBar activity="website" sidebarOpen onActivity={select} onSettings={vi.fn()} onHelp={vi.fn()} />); for (const name of ["Website", "Assets", "Design", "Reusable Sections", "History", "Project Settings", "Help and Shortcuts"]) expect(screen.getByRole("button", { name })).toBeDefined(); fireEvent.click(screen.getByRole("button", { name: "Assets" })); expect(select).toHaveBeenCalledWith("assets"); expect(screen.getByRole("button", { name: "Website" }).getAttribute("aria-current")).toBe("page"); });
  it("uses a predictable account menu", () => { render(<TitleBar workspaceName="Studio" projectName="Site" pageName="Home" userName="Alex Smith" canShare activeTasks={0} failedTasks={0} agentOpen onSearch={vi.fn()} onShare={vi.fn()} onTasks={vi.fn()} onToggleAgent={vi.fn()} onSignOut={vi.fn()} />); fireEvent.click(screen.getByRole("button", { name: /Account menu/ })); for (const name of ["Account", "All Projects", "Workspaces", "Sign out"]) expect(screen.getByRole("menuitem", { name })).toBeDefined(); expect(screen.getByText("Studio")).toBeDefined(); expect(screen.getByText("Site")).toBeDefined(); expect(screen.getByText("Home")).toBeDefined(); });
  it("provides navigation, page, device, zoom, selection, and overflow controls", () => { const page = vi.fn(); const device = vi.fn(); const zoom = vi.fn(); render(<PreviewStage frame={{ current: null }} frameSrc="/preview/token" sandboxTitle="Preview" device="desktop" route="/" host="site.test" pages={[{ id: "home", name: "Home", route: "/" }, { id: "about", name: "About", route: "/about" }]} status="ready" selectMode={false} fullScreen={false} theme="light" zoom={100} fit={false} canBack canForward={false} onBack={vi.fn()} onForward={vi.fn()} onPage={page} onDevice={device} onZoom={zoom} onFit={vi.fn()} onTheme={vi.fn()} onSelectMode={vi.fn()} onRefresh={vi.fn()} onFullScreen={vi.fn()} />); expect(screen.getByRole("button", { name: "Forward" })).toHaveProperty("disabled", true); fireEvent.change(screen.getByLabelText("Current preview page"), { target: { value: "/about" } }); expect(page).toHaveBeenCalledWith("/about"); fireEvent.click(screen.getByRole("button", { name: "Phone" })); expect(device).toHaveBeenCalledWith("mobile"); fireEvent.click(screen.getByRole("button", { name: "Zoom in" })); expect(zoom).toHaveBeenCalled(); fireEvent.click(screen.getByRole("button", { name: "More preview options" })); expect(screen.getByRole("menuitem", { name: /Open preview in new tab/ })).toBeDefined(); expect(screen.getByRole("status").textContent).toContain("Preview ready"); });
});
