import { randomUUID } from "node:crypto";
import { afterAll, beforeEach, describe, expect, it } from "vitest";
import { and, eq } from "drizzle-orm";
import { AIFollowUpService, promoteQueuedFollowUp } from "./service";
import { GenerationJobService } from "@/domain/ai/job-service";
import { PageTreeService } from "@/domain/pages/service";
import { ProjectService } from "@/domain/projects/service";
import { WorkspaceService } from "@/domain/workspaces/service";
import { db, sql } from "@/server/db/client";
import { aiFollowUpQueue, generationJobs, pageNodes, pageVersions, projectMembers, users } from "@/server/db/schema";

async function setup() { const id = randomUUID(); const [owner] = await db.insert(users).values({ id, email: `${id}@test.dev`, normalizedEmail: `${id}@test.dev`, displayName: "Owner" }).returning(); const workspace = await new WorkspaceService().create(owner!.id, { name: "Workspace" }); const project = await new ProjectService().create(owner!.id, { workspaceId: workspace.id, name: "Site" }); const page = await new PageTreeService().create(owner!.id, { projectId: project.id, type: "page", name: "Home" }); return { owner: owner!, project, page }; }
describe.sequential("Phase 14 AI follow-up queue", () => {
  beforeEach(async () => { await sql`TRUNCATE TABLE ai_follow_up_queue, generation_job_media, page_versions, ai_job_rate_limits, generation_jobs, ai_messages, ai_conversations, page_nodes, audit_events, project_members, projects, workspaces, users RESTART IDENTITY CASCADE`; });
  afterAll(async () => { await sql.end(); });
  it("keeps FIFO order, permits pre-claim edit/cancel, and protects one active target", async () => { const { owner, project, page } = await setup(); const jobs = new GenerationJobService(); const active = await jobs.createPageJob(owner.id, { projectId: project.id, pageId: page.id, content: "First", selectedMediaIds: [] }); const queue = new AIFollowUpService(); const first = await queue.create(owner.id, { projectId: project.id, targetType: "page", targetId: page.id, prompt: "Second", selectedMediaIds: [] }); const second = await queue.create(owner.id, { projectId: project.id, targetType: "page", targetId: page.id, prompt: "Third", selectedMediaIds: [] }); expect((await queue.list(owner.id, project.id)).map((item) => item.id)).toEqual([first.id, second.id]); await queue.edit(owner.id, project.id, second.id, { prompt: "Third, edited", selectedMediaIds: [] }); await jobs.requestCancellation(owner.id, project.id, active.job.id); /* Cancelling a queued job promotes the next follow-up right there, so ordering never waits for a scheduled sweep. */ expect((await db.select().from(aiFollowUpQueue).where(eq(aiFollowUpQueue.id, first.id)))[0]).toMatchObject({ status: "claimed" }); expect(await promoteQueuedFollowUp()).toBeNull(); expect(await db.select().from(generationJobs).where(and(eq(generationJobs.projectId, project.id), eq(generationJobs.status, "queued")))).toHaveLength(1); await queue.cancel(owner.id, project.id, second.id); expect((await db.select().from(aiFollowUpQueue).where(eq(aiFollowUpQueue.id, second.id)))[0]).toMatchObject({ status: "cancelled", prompt: "Third, edited" }); });
  it("pauses a stale base instead of applying to unexpected content", async () => { const { owner, project, page } = await setup(); const active = await new GenerationJobService().createPageJob(owner.id, { projectId: project.id, pageId: page.id, content: "First", selectedMediaIds: [] }); const item = await new AIFollowUpService().create(owner.id, { projectId: project.id, targetType: "page", targetId: page.id, prompt: "Follow", selectedMediaIds: [] }); const [version] = await db.insert(pageVersions).values({ projectId: project.id, pageId: page.id, versionNumber: 1, sourceCode: "export default function Page(){return <main/>}", manifest: {}, seoMetadata: {}, changeSummary: {}, sourceHash: "a".repeat(64), createdByUserId: owner.id }).returning(); await db.update(pageNodes).set({ currentVersionId: version!.id }).where(eq(pageNodes.id, page.id)); await new GenerationJobService().requestCancellation(owner.id, project.id, active.job.id); expect(await promoteQueuedFollowUp()).toBeNull(); expect((await db.select().from(aiFollowUpQueue).where(eq(aiFollowUpQueue.id, item.id)))[0]).toMatchObject({ status: "paused", pauseReason: expect.stringMatching(/changed/) }); });
  it("revalidates membership before claim", async () => { const { owner, project, page } = await setup(); const collaboratorId = randomUUID(); const [collaborator] = await db.insert(users).values({ id: collaboratorId, email: `${collaboratorId}@test.dev`, normalizedEmail: `${collaboratorId}@test.dev`, displayName: "Collaborator" }).returning(); await db.insert(projectMembers).values({ projectId: project.id, userId: collaborator!.id }); const active = await new GenerationJobService().createPageJob(owner.id, { projectId: project.id, pageId: page.id, content: "First", selectedMediaIds: [] }); const item = await new AIFollowUpService().create(collaborator!.id, { projectId: project.id, targetType: "page", targetId: page.id, prompt: "Follow", selectedMediaIds: [] }); await db.delete(projectMembers).where(and(eq(projectMembers.projectId, project.id), eq(projectMembers.userId, collaborator!.id))); await new GenerationJobService().requestCancellation(owner.id, project.id, active.job.id); await promoteQueuedFollowUp(); expect((await db.select().from(aiFollowUpQueue).where(eq(aiFollowUpQueue.id, item.id)))[0]).toMatchObject({ status: "paused", pauseReason: expect.stringMatching(/no longer have access/) }); });
});
