import { and, asc, count, eq, inArray, sql as drizzleSql } from "drizzle-orm";
import { GenerationJobService } from "@/domain/ai/job-service";
import { DomainError } from "@/domain/shared/errors";
import { db, type Database } from "@/server/db/client";
import { aiFollowUpQueue, auditEvents, buildingBlocks, generationJobs, mediaAssets, pageNodes } from "@/server/db/schema";
import { ProjectAccessService } from "@/server/permissions/project-access";
import { editFollowUpSchema, queueFollowUpSchema } from "./schemas";

export const AI_QUEUE_LIMITS = { project: 20, user: 10 } as const;
const active = ["queued", "preparing_context", "generating", "validating", "applying"] as const;

export class AIFollowUpService {
  constructor(private readonly database: Database = db, private readonly access = new ProjectAccessService()) {}
  private async target(projectId: string, type: "page" | "building_block", id: string) {
    if (type === "page") { const [row] = await this.database.select({ id: pageNodes.id, version: pageNodes.currentVersionId }).from(pageNodes).where(and(eq(pageNodes.projectId, projectId), eq(pageNodes.id, id), eq(pageNodes.type, "page"), drizzleSql`${pageNodes.deletedAt} IS NULL`)).limit(1); return row; }
    const [row] = await this.database.select({ id: buildingBlocks.id, version: buildingBlocks.currentVersionId }).from(buildingBlocks).where(and(eq(buildingBlocks.projectId, projectId), eq(buildingBlocks.id, id), drizzleSql`${buildingBlocks.deletedAt} IS NULL`)).limit(1); return row;
  }
  private async validateMedia(projectId: string, ids: string[]) { const unique = [...new Set(ids)]; const rows = unique.length ? await this.database.select({ id: mediaAssets.id }).from(mediaAssets).where(and(eq(mediaAssets.projectId, projectId), inArray(mediaAssets.id, unique), drizzleSql`${mediaAssets.deletedAt} IS NULL`)) : []; if (rows.length !== unique.length) throw new DomainError("NOT_FOUND", "One or more selected images are no longer available in this project."); return unique; }
  async create(userId: string, input: unknown) {
    const value = queueFollowUpSchema.parse(input); await this.access.requireProjectAccess(userId, value.projectId);
    const target = await this.target(value.projectId, value.targetType, value.targetId); if (!target) throw new DomainError("NOT_FOUND", "That page or reusable section is no longer available.");
    const media = await this.validateMedia(value.projectId, value.selectedMediaIds);
    const [projectCount, userCount] = await Promise.all([
      this.database.select({ value: count() }).from(aiFollowUpQueue).where(and(eq(aiFollowUpQueue.projectId, value.projectId), eq(aiFollowUpQueue.status, "queued"))),
      this.database.select({ value: count() }).from(aiFollowUpQueue).where(and(eq(aiFollowUpQueue.creatorUserId, userId), eq(aiFollowUpQueue.status, "queued"))),
    ]);
    if ((projectCount[0]?.value ?? 0) >= AI_QUEUE_LIMITS.project) throw new DomainError("VALIDATION", "This project already has too many follow-up instructions. Cancel one before adding another.");
    if ((userCount[0]?.value ?? 0) >= AI_QUEUE_LIMITS.user) throw new DomainError("VALIDATION", "You already have too many follow-up instructions. Cancel one before adding another.");
    const [item] = await this.database.insert(aiFollowUpQueue).values({ projectId: value.projectId, targetType: value.targetType, targetId: value.targetId, creatorUserId: userId, prompt: value.prompt, selectedMediaIds: media, selectedElement: value.selection, baseVersionId: target.version }).returning();
    if (!item) throw new Error("Follow-up insert failed.");
    await this.database.insert(auditEvents).values({ projectId: value.projectId, userId, action: "ai.queue_created", entityType: "ai_follow_up", entityId: item.id, metadata: { targetType: value.targetType, targetId: value.targetId, position: item.sequence } }); return item;
  }
  async list(userId: string, projectId: string, targetType?: "page" | "building_block", targetId?: string) { await this.access.requireProjectAccess(userId, projectId); const filters = [eq(aiFollowUpQueue.projectId, projectId)]; if (targetType) filters.push(eq(aiFollowUpQueue.targetType, targetType)); if (targetId) filters.push(eq(aiFollowUpQueue.targetId, targetId)); const rows = await this.database.select().from(aiFollowUpQueue).where(and(...filters)).orderBy(asc(aiFollowUpQueue.sequence)).limit(50); return rows.map((row) => ({ ...row, editable: row.creatorUserId === userId && ["queued", "paused"].includes(row.status), prompt: row.creatorUserId === userId ? row.prompt : "Follow-up instruction" })); }
  async edit(userId: string, projectId: string, itemId: string, input: unknown) { const value = editFollowUpSchema.parse(input); await this.access.requireProjectAccess(userId, projectId); const [current] = await this.database.select().from(aiFollowUpQueue).where(and(eq(aiFollowUpQueue.id, itemId), eq(aiFollowUpQueue.projectId, projectId), eq(aiFollowUpQueue.creatorUserId, userId), inArray(aiFollowUpQueue.status, ["queued", "paused"]))).limit(1); if (!current) throw new DomainError("CONFLICT", "This follow-up has already started or is not yours to edit."); const target = await this.target(projectId, current.targetType, current.targetId); if (!target) throw new DomainError("NOT_FOUND", "That page or reusable section is no longer available. Cancel this follow-up or retarget it."); const media = await this.validateMedia(projectId, value.selectedMediaIds); const [item] = await this.database.update(aiFollowUpQueue).set({ prompt: value.prompt, selectedMediaIds: media, selectedElement: value.selection, baseVersionId: target.version, status: "queued", pauseReason: null, updatedAt: new Date() }).where(and(eq(aiFollowUpQueue.id, itemId), eq(aiFollowUpQueue.status, current.status))).returning(); if (!item) throw new DomainError("CONFLICT", "This follow-up started while you were editing it."); await this.database.insert(auditEvents).values({ projectId, userId, action: "ai.queue_edited", entityType: "ai_follow_up", entityId: item.id, metadata: { resumed: current.status === "paused" } }); return item; }
  async cancel(userId: string, projectId: string, itemId: string) { await this.access.requireProjectAccess(userId, projectId); const [item] = await this.database.update(aiFollowUpQueue).set({ status: "cancelled", cancelledAt: new Date(), updatedAt: new Date() }).where(and(eq(aiFollowUpQueue.id, itemId), eq(aiFollowUpQueue.projectId, projectId), eq(aiFollowUpQueue.creatorUserId, userId), inArray(aiFollowUpQueue.status, ["queued", "paused"]))).returning(); if (!item) throw new DomainError("CONFLICT", "This follow-up has already started or is not yours to cancel."); await this.database.insert(auditEvents).values({ projectId, userId, action: "ai.queue_cancelled", entityType: "ai_follow_up", entityId: item.id }); return item; }
}

/** Claims exactly one FIFO follow-up by creating its ordinary protected generation job. */
export async function promoteQueuedFollowUp(database: Database = db) {
  const candidates = await database.select().from(aiFollowUpQueue).where(eq(aiFollowUpQueue.status, "queued")).orderBy(asc(aiFollowUpQueue.sequence)).limit(20);
  for (const item of candidates) {
    const [running] = await database.select({ id: generationJobs.id }).from(generationJobs).where(and(eq(generationJobs.projectId, item.projectId), eq(generationJobs.targetId, item.targetId), inArray(generationJobs.status, [...active]))).limit(1); if (running) continue;
    const target = item.targetType === "page" ? (await database.select({ version: pageNodes.currentVersionId }).from(pageNodes).where(and(eq(pageNodes.id, item.targetId), eq(pageNodes.projectId, item.projectId), drizzleSql`${pageNodes.deletedAt} IS NULL`)).limit(1))[0] : (await database.select({ version: buildingBlocks.currentVersionId }).from(buildingBlocks).where(and(eq(buildingBlocks.id, item.targetId), eq(buildingBlocks.projectId, item.projectId), drizzleSql`${buildingBlocks.deletedAt} IS NULL`)).limit(1))[0];
    if (!target || target.version !== item.baseVersionId) { const reason = !target ? "The target no longer exists. Review or cancel this follow-up." : "The page or reusable section changed while this was waiting. Review or retarget the follow-up."; await database.update(aiFollowUpQueue).set({ status: "paused", pauseReason: reason, updatedAt: new Date() }).where(and(eq(aiFollowUpQueue.id, item.id), eq(aiFollowUpQueue.status, "queued"))); await database.insert(auditEvents).values({ projectId: item.projectId, userId: item.creatorUserId, action: "ai.queue_paused", entityType: "ai_follow_up", entityId: item.id, metadata: { reason: !target ? "target_missing" : "base_changed" } }); continue; }
    try { const service = new GenerationJobService(database); const input = { projectId: item.projectId, [`${item.targetType === "page" ? "page" : "block"}Id`]: item.targetId, content: item.prompt, selectedMediaIds: item.selectedMediaIds, selection: item.selectedElement }; const result = item.targetType === "page" ? await service.createPageJob(item.creatorUserId, input, item.id) : await service.createBlockJob(item.creatorUserId, input, item.id); await database.update(aiFollowUpQueue).set({ status: "claimed", generationJobId: result.job.id, claimedAt: new Date(), updatedAt: new Date() }).where(and(eq(aiFollowUpQueue.id, item.id), eq(aiFollowUpQueue.status, "queued"))); await database.insert(auditEvents).values({ projectId: item.projectId, userId: item.creatorUserId, action: "ai.queue_claimed", entityType: "ai_follow_up", entityId: item.id, metadata: { generationJobId: result.job.id } }); return result.job; }
    catch (error) { const [existing] = await database.select().from(generationJobs).where(eq(generationJobs.queueItemId, item.id)).limit(1); if (existing) { await database.update(aiFollowUpQueue).set({ status: "claimed", generationJobId: existing.id, claimedAt: new Date(), updatedAt: new Date() }).where(eq(aiFollowUpQueue.id, item.id)); return existing; } if (error instanceof DomainError && error.code === "CONFLICT") continue; const reason = error instanceof DomainError && error.code === "ACCESS_DENIED" ? "You no longer have access to run this follow-up. Ask a project owner for access or cancel it." : "Something this follow-up needs is no longer available. Review its target and images before trying again."; await database.update(aiFollowUpQueue).set({ status: "paused", pauseReason: reason, updatedAt: new Date() }).where(and(eq(aiFollowUpQueue.id, item.id), eq(aiFollowUpQueue.status, "queued"))); await database.insert(auditEvents).values({ projectId: item.projectId, userId: item.creatorUserId, action: "ai.queue_paused", entityType: "ai_follow_up", entityId: item.id, metadata: { reason: error instanceof DomainError ? error.code : "validation_failed" } }); }
  } return null;
}

export async function finalizeQueuedFollowUp(jobId: string, outcome: string, database: Database = db) { const [item] = await database.update(aiFollowUpQueue).set({ status: "completed", updatedAt: new Date() }).where(and(eq(aiFollowUpQueue.generationJobId, jobId), eq(aiFollowUpQueue.status, "claimed"))).returning(); if (item) await database.insert(auditEvents).values({ projectId: item.projectId, userId: item.creatorUserId, action: "ai.queue_completed", entityType: "ai_follow_up", entityId: item.id, metadata: { generationJobId: jobId, outcome } }); return item ?? null; }
