import { randomUUID } from "node:crypto";
import { afterAll, beforeEach, describe, expect, it } from "vitest";
import { eq } from "drizzle-orm";
import { db, sql } from "@/server/db/client";
import { aiMessages, changeSets, pageNodes, pageVersions, projectMembers, users } from "@/server/db/schema";
import { WorkspaceService } from "@/domain/workspaces/service";
import { ProjectService } from "@/domain/projects/service";
import { PageTreeService } from "@/domain/pages/service";
import { GenerationJobService, claimGenerationJob } from "@/domain/ai/job-service";
import { AIOrchestrationService } from "@/domain/ai/orchestration-service";
import type { AIProvider, AIRequest, AIResponse, StructuredValidator } from "@/domain/ai/provider";
import { PreviewManifestService } from "@/generated-runtime/manifest/service";
import { GeneratedPageContentProvider } from "@/generated-runtime/preview/generated-page-provider";
import { renderPreviewDocument } from "@/generated-runtime/preview/render-document";
import { fixtureProviderResolver } from "@/domain/ai/testing/provider-fixtures";

/** Media as the sandboxed Preview resolves it: a session URL, never a storage key. */
const previewMedia = (mediaId: string) => ({ url: `/api/preview/media/${mediaId}`, width: 800, height: 600, altText: null });


const validSource = `<main class="c-page" data-canvas-id="page"><section class="c-section c-container" data-canvas-id="intro"><h1>Generated website</h1><p class="c-muted">Responsive page content.</p></section></main>`;
class FixtureProvider implements AIProvider { readonly capabilities = { structuredOutput: true, vision: true }; name="fixture"; model="fixture-1"; constructor(private source=validSource, private js="") {} async generateText(): Promise<AIResponse>{return {text:"unused",provider:this.name,model:this.model}} async generateStructured<T>(_request: AIRequest, validator: StructuredValidator<T>): Promise<AIResponse<T>> { const value={schemaVersion:1,html:this.source,css:"",js:this.js,referencedMediaIds:[],summary:{headline:"Updated",changes:["Created responsive content"],limitations:[]}}; return {text:JSON.stringify(value),structuredData:validator.parse(value),provider:this.name,model:this.model,usage:{totalTokens:12}}; } }
class CorrectingFixtureProvider implements AIProvider { readonly capabilities = { structuredOutput: true, vision: true };
  name="fixture"; model="fixture-1"; calls: AIRequest[]=[];
  constructor(private readonly sources: string[]) {}
  async generateText(): Promise<AIResponse>{return {text:"unused",provider:this.name,model:this.model}}
  async generateStructured<T>(request: AIRequest, validator: StructuredValidator<T>): Promise<AIResponse<T>> {
    this.calls.push(request);
    const value={schemaVersion:1,html:this.sources[this.calls.length-1]!,css:"",js:"",referencedMediaIds:[],summary:{headline:"Updated",changes:["Created responsive content"],limitations:[]}};
    return {text:JSON.stringify(value),structuredData:validator.parse(value),provider:this.name,model:this.model,usage:{totalTokens:12}};
  }
}
/** Mirrors the real provider: the response schema is applied inside `generateStructured`. */
class SummaryFixtureProvider implements AIProvider { readonly capabilities = { structuredOutput: true, vision: true };
  name="fixture"; model="fixture-1";
  constructor(private readonly summary: unknown) {}
  async generateText(): Promise<AIResponse>{return {text:"unused",provider:this.name,model:this.model}}
  async generateStructured<T>(_request: AIRequest, validator: StructuredValidator<T>): Promise<AIResponse<T>> {
    const value={schemaVersion:1,html:validSource,css:"",js:"",referencedMediaIds:[],summary:this.summary};
    return {text:JSON.stringify(value),structuredData:validator.parse(value),provider:this.name,model:this.model,usage:{totalTokens:12}};
  }
}
async function user(label:string){const id=randomUUID();const [record]=await db.insert(users).values({id,email:`${label}-${id}@test.dev`,normalizedEmail:`${label}-${id}@test.dev`,displayName:label}).returning();return record!}
async function setup(){const owner=await user("owner");const workspace=await new WorkspaceService().create(owner.id,{name:"Workspace"});const project=await new ProjectService().create(owner.id,{workspaceId:workspace.id,name:"Site"});const page=await new PageTreeService().create(owner.id,{projectId:project.id,type:"page",name:"Home"});return {owner,project,page}}

describe.sequential("Phase 8 page generation",()=>{
  process.env.PREVIEW_TOKEN_SECRET="phase-eight-test-preview-secret-value";
  beforeEach(async()=>{await sql`TRUNCATE TABLE generation_job_media, page_versions, ai_job_rate_limits, generation_jobs, ai_messages, ai_conversations, project_instructions, media_assets, media_folders, page_nodes, audit_events, editing_leases, project_invites, project_members, auth_rate_limits, sessions, auth_credentials, projects, workspaces, users RESTART IDENTITY CASCADE`});
  afterAll(async()=>{await sql.end()});
  it("creates immutable v1 then v2 and persists concise summaries",async()=>{const {owner,project,page}=await setup();const jobs=new GenerationJobService();const first=await jobs.createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"Create the homepage",selectedMediaIds:[]});expect(first.job).toMatchObject({operation:"page_generate",basePageVersionId:null});await claimGenerationJob("worker");const orchestrator=new AIOrchestrationService(db,undefined,undefined,fixtureProviderResolver(()=>new FixtureProvider()));const done1=await orchestrator.process(first.job.id);expect(done1).toMatchObject({status:"completed"});const [v1]=await db.select().from(pageVersions);expect(v1).toMatchObject({versionNumber:1,sourceFormat:"static_html",document:{schemaVersion:1,html:validSource,css:"",js:""},seoMetadata:{title:null,description:null}});const second=await jobs.createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"Make it tighter",selectedMediaIds:[]});expect(second.job).toMatchObject({operation:"page_modify",basePageVersionId:v1!.id});await claimGenerationJob("worker");await orchestrator.process(second.job.id);const versions=await db.select().from(pageVersions);expect(versions.map(v=>v.versionNumber).sort()).toEqual([1,2]);expect(versions.find(v=>v.id===v1!.id)?.document).toMatchObject({html:validSource});const [current]=await db.select().from(pageNodes).where(eq(pageNodes.id,page.id));expect(current?.currentVersionId).not.toBe(v1!.id);const messages=await db.select().from(aiMessages);expect(messages.filter(m=>m.role==="assistant")).toHaveLength(2);expect(messages.find(m=>m.role==="assistant")?.content).not.toContain("export default");});
  it("rejects same-page concurrency but allows different pages",async()=>{const {owner,project,page}=await setup();const secondPage=await new PageTreeService().create(owner.id,{projectId:project.id,type:"page",name:"Contact"});const jobs=new GenerationJobService();await jobs.createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"One",selectedMediaIds:[]});await expect(jobs.createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"Two",selectedMediaIds:[]})).rejects.toThrow(/already updating/);await expect(jobs.createPageJob(owner.id,{projectId:project.id,pageId:secondPage.id,content:"Contact",selectedMediaIds:[]})).resolves.toBeDefined();});
  it("rejects stale results and leaves the newer version current",async()=>{const {owner,project,page}=await setup();const jobs=new GenerationJobService();const request=await jobs.createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"Create",selectedMediaIds:[]});await claimGenerationJob("worker");const fakeVersionId=randomUUID();await db.insert(pageVersions).values({id:fakeVersionId,projectId:project.id,pageId:page.id,versionNumber:1,document:{schemaVersion:1,html:validSource,css:"",js:"",metadata:null},manifest:{referencedMediaIds:[]},seoMetadata:{},changeSummary:{},sourceHash:"a".repeat(64),createdByUserId:owner.id});await db.update(pageNodes).set({currentVersionId:fakeVersionId}).where(eq(pageNodes.id,page.id));const result=await new AIOrchestrationService(db,undefined,undefined,fixtureProviderResolver(()=>new FixtureProvider())).process(request.job.id);expect(result).toMatchObject({status:"failed",errorCode:"AI_PAGE_STALE"});expect((await db.select().from(pageVersions))).toHaveLength(1);expect((await db.select().from(pageNodes))[0]?.currentVersionId).toBe(fakeVersionId);});
  it("never activates invalid source or a cancelled response",async()=>{const {owner,project,page}=await setup();const jobs=new GenerationJobService();const invalid=await jobs.createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"Invalid",selectedMediaIds:[]});await claimGenerationJob("worker");const failed=await new AIOrchestrationService(db,undefined,undefined,fixtureProviderResolver(()=>new FixtureProvider(`<main class="c-page" data-canvas-id="page"><h1>Home</h1></main>`,`fetch("/api");`))).process(invalid.job.id);expect(failed).toMatchObject({status:"failed",errorCode:"AI_GENERATED_DOCUMENT_INVALID"});expect(await db.select().from(pageVersions)).toHaveLength(0);const cancelled=await jobs.createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"Cancel",selectedMediaIds:[]});await jobs.requestCancellation(owner.id,project.id,cancelled.job.id);await new AIOrchestrationService(db,undefined,undefined,fixtureProviderResolver(()=>new FixtureProvider())).process(cancelled.job.id);expect(await db.select().from(pageVersions)).toHaveLength(0);});
  it("preserves the previous active version when a later candidate fails source validation",async()=>{const {owner,project,page}=await setup();const jobs=new GenerationJobService();const initial=await jobs.createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"Create",selectedMediaIds:[]});await claimGenerationJob("worker");await new AIOrchestrationService(db,undefined,undefined,fixtureProviderResolver(()=>new FixtureProvider())).process(initial.job.id);const [baseline]=await db.select().from(pageVersions);const update=await jobs.createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"Add tracking",selectedMediaIds:[]});await claimGenerationJob("worker");const failed=await new AIOrchestrationService(db,undefined,undefined,fixtureProviderResolver(()=>new FixtureProvider(`<main class="c-page" data-canvas-id="page"><h1>Home</h1></main>`,`fetch("/api");`))).process(update.job.id);const [current]=await db.select().from(pageNodes).where(eq(pageNodes.id,page.id));expect(failed).toMatchObject({status:"failed",errorCode:"AI_GENERATED_DOCUMENT_INVALID"});expect(current?.currentVersionId).toBe(baseline!.id);expect(await db.select().from(pageVersions)).toHaveLength(1);});
  it("repairs safe static IDs, corrects one rejected candidate, and persists useful terminal diagnostics",async()=>{const {owner,project,page}=await setup();const jobs=new GenerationJobService();const repair=await jobs.createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"Create",selectedMediaIds:[]});await claimGenerationJob("worker");const repaired=await new AIOrchestrationService(db,undefined,undefined,fixtureProviderResolver(()=>new FixtureProvider(`<main class="c-page" data-canvas-id="Hero Main">Home</main>`))).process(repair.job.id);expect(repaired).toMatchObject({status:"completed"});expect((await db.select().from(pageVersions))[0]?.document).toMatchObject({html:expect.stringContaining(`data-canvas-id="hero-main"`)});const invalid=`<main class="c-page" data-canvas-id="feature-card-1"><section data-canvas-id="feature-card-1">Features</section></main>`;const corrected=`<main class="c-page" data-canvas-id="feature-card-1"><section data-canvas-id="features-grid">Features updated</section></main>`;const provider=new CorrectingFixtureProvider([invalid,corrected]);const retry=await jobs.createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"Update",selectedMediaIds:[]});await claimGenerationJob("worker");const result=await new AIOrchestrationService(db,undefined,undefined,fixtureProviderResolver(()=>provider)).process(retry.job.id);expect(result).toMatchObject({status:"completed"});expect(provider.calls).toHaveLength(2);expect(provider.calls[1]?.messages.at(-1)?.parts[0]).toMatchObject({type:"text",text:expect.stringContaining("feature-card-")});let versions=await db.select().from(pageVersions);expect(versions).toHaveLength(2);expect(versions.find((version)=>version.id===result?.resultPageVersionId)?.document).toMatchObject({html:corrected});const terminal=await jobs.createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"Invalid twice",selectedMediaIds:[]});await claimGenerationJob("worker");const rejected=await new AIOrchestrationService(db,undefined,undefined,fixtureProviderResolver(()=>new CorrectingFixtureProvider([invalid,invalid,invalid]))).process(terminal.job.id);expect(rejected).toMatchObject({status:"failed",errorDiagnostic:expect.stringMatching(/invalid data-canvas-id values:.*feature-card-.*expected static literals matching/)});versions=await db.select().from(pageVersions);expect(versions).toHaveLength(2);});
  it("completes with an over-length summary and keeps the change set within its column",async()=>{const {owner,project}=await setup();const longName="N".repeat(120);const page=await new PageTreeService().create(owner.id,{projectId:project.id,type:"page",name:longName});const summary={headline:"H".repeat(180),changes:["C".repeat(240)],limitations:["L".repeat(260)]};const request=await new GenerationJobService().createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"Create",selectedMediaIds:[]});await claimGenerationJob("worker");const result=await new AIOrchestrationService(db,undefined,undefined,fixtureProviderResolver(()=>new SummaryFixtureProvider(summary))).process(request.job.id);expect(result).toMatchObject({status:"completed"});const [version]=await db.select().from(pageVersions);expect(version?.document).toMatchObject({html:validSource});expect(version?.changeSummary).toEqual({headline:"H".repeat(120),changes:["C".repeat(200)],limitations:["L".repeat(200)]});const [changeSet]=await db.select().from(changeSets).where(eq(changeSets.id,version!.changeSetId!));expect(changeSet?.summary).toBe(`${longName}: ${"H".repeat(120)}`);});
  it("isolates versions and generated preview while preserving sandbox content",async()=>{const {owner,project,page}=await setup();const stranger=await user("stranger");const request=await new GenerationJobService().createPageJob(owner.id,{projectId:project.id,pageId:page.id,content:"Create",selectedMediaIds:[]});await claimGenerationJob("worker");await new AIOrchestrationService(db,undefined,undefined,fixtureProviderResolver(()=>new FixtureProvider())).process(request.job.id);const manifest=(await new PreviewManifestService().createSession(owner.id,project.id)).manifest;expect(manifest.pages[0]).toMatchObject({contentStatus:"generated",currentVersionId:expect.any(String)});const generated=await new GeneratedPageContentProvider().get(project.id,page.id,manifest.pages[0]!.currentVersionId!, previewMedia);expect(generated?.composed.html).toContain("Generated website");const html=renderPreviewDocument({manifest,nonce:"nonce",parentOrigin:"http://localhost:3000",instanceId:randomUUID(),initialRoute:"/",initialMode:"dark",generated:generated!.composed});expect(html).toContain("generated-root");expect(html).toContain("data-theme=dark");await expect(new GenerationJobService().get(stranger.id,project.id,request.job.id)).rejects.toThrow(/do not have access/);await db.insert(projectMembers).values({projectId:project.id,userId:stranger.id});await db.delete(projectMembers).where(eq(projectMembers.userId,stranger.id));await expect(new GenerationJobService().get(stranger.id,project.id,request.job.id)).rejects.toThrow(/do not have access/);});
});
